// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svuhmpmzadkqrodugcow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2dWhtcG16YWRrcXJvZHVnY293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDU3MzUsImV4cCI6MjA3MDIyMTczNX0.B1wsQq_7BOlsYuA2qKvt1V2fyO2spU-uzb0FZJoq09Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});